import React from 'react'

export default function Privacy() {
  return (
    <div className="min-h-screen bg-gray-50 font-sans text-gray-900 pb-20">
      <header className="bg-white border-b border-gray-200 py-6">
        <div className="max-w-4xl mx-auto px-6 flex justify-between items-center">
          <div className="flex items-center gap-3">
            <span className="text-2xl font-black tracking-tight">Crudhub</span>
          </div>
          <a href="/" className="text-sm font-bold bg-gray-100 hover:bg-gray-200 text-gray-800 px-4 py-2 rounded-lg transition-colors">Back to Home</a>
        </div>
      </header>
      
      <main className="max-w-4xl mx-auto px-6 mt-12 bg-white p-8 md:p-12 rounded-2xl shadow-sm border border-gray-100">
        <h1 className="text-3xl font-black mb-2">Privacy Policy</h1>
        <p className="text-gray-500 font-medium mb-8">Last Updated: {new Date().toLocaleDateString()}</p>
        
        <div className="space-y-8 text-gray-700">
          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">1. Information We Collect</h2>
            <p>SolutionPRO Technologies collects necessary business information to provide the Crudhub service. This includes your business name, WhatsApp phone number, and digital catalog data (product names, prices, and images). We also store a secure 4-digit PIN generated by you for dashboard access.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">2. How We Use Your Data</h2>
            <p>Your data is used exclusively to operate your digital storefront, authenticate your login access, and facilitate automated WhatsApp order routing. We use your contact information to send automated subscription reminders and platform updates.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">3. Data Security and NDPR Compliance</h2>
            <p>We are committed to data protection principles in accordance with standard regulations. Our backend infrastructure utilizes secure cloud environments to protect your information against unauthorized access, alteration, or destruction. We do not sell, rent, or trade your personal or business data to third parties.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">4. End-Consumer Data</h2>
            <p>End-consumer data (such as names and delivery addresses entered during checkout) is routed directly to the merchant's WhatsApp. Crudhub temporarily processes this data strictly to format the order message and does not use end-consumer data for marketing purposes.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">5. Your Rights</h2>
            <p>You have the right to request the deletion of your account and associated data from our servers. To initiate a data deletion request, please contact our support team at realsolutionpro@outlook.com or +234 902 811 6376.</p>
          </section>
        </div>
      </main>
    </div>
  )
}
